sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t kryz81/docker-react .

script:
  - docker run -e CI=true kryz81/docker-react npm run test -- --coverage
