sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t kryz81/docker-react .

script:
  - docker run -e CI=true kryz81/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-724285995924
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
